"""Initial migration - create autoscraper tables

Revision ID: 9ff4be26961c
Revises: 
Create Date: 2025-08-30 14:10:21.264898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff4be26961c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoscraper_engine_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'PAUSED', 'ERROR', 'MAINTENANCE', name='enginestatus'), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('active_jobs_count', sa.Integer(), nullable=True),
    sa.Column('queued_jobs_count', sa.Integer(), nullable=True),
    sa.Column('total_jobs_processed', sa.Integer(), nullable=True),
    sa.Column('total_jobs_today', sa.Integer(), nullable=True),
    sa.Column('success_rate_today', sa.Float(), nullable=True),
    sa.Column('average_job_duration', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('system_load', sa.Float(), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=True),
    sa.Column('error_count_today', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_engine_heartbeat', 'autoscraper_engine_state', ['last_heartbeat'], unique=False)
    op.create_index('idx_engine_status', 'autoscraper_engine_state', ['status'], unique=False)
    op.create_table('autoscraper_job_boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('RSS', 'HTML', 'API', 'HYBRID', name='jobboardtype'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('rss_url', sa.String(length=500), nullable=True),
    sa.Column('selectors', sa.JSON(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('rate_limit_delay', sa.Integer(), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('request_timeout', sa.Integer(), nullable=True),
    sa.Column('retry_attempts', sa.Integer(), nullable=True),
    sa.Column('quality_threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('total_scrapes', sa.Integer(), nullable=True),
    sa.Column('successful_scrapes', sa.Integer(), nullable=True),
    sa.Column('failed_scrapes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_job_board_active', 'autoscraper_job_boards', ['is_active'], unique=False)
    op.create_index('idx_job_board_type', 'autoscraper_job_boards', ['type'], unique=False)
    op.create_table('autoscraper_schedule_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('max_concurrent_jobs', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_delay_minutes', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_board_id'], ['autoscraper_job_boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_enabled', 'autoscraper_schedule_configs', ['is_enabled'], unique=False)
    op.create_index('idx_schedule_next_run', 'autoscraper_schedule_configs', ['next_run_at'], unique=False)
    op.create_table('autoscraper_scrape_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_board_id', sa.UUID(), nullable=False),
    sa.Column('schedule_config_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('MANUAL', 'SCHEDULED', 'CONTINUOUS', name='scrapejobmode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='scrapejobstatus'), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('total_items_found', sa.Integer(), nullable=True),
    sa.Column('total_items_created', sa.Integer(), nullable=True),
    sa.Column('total_items_updated', sa.Integer(), nullable=True),
    sa.Column('total_items_skipped', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_board_id'], ['autoscraper_job_boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_config_id'], ['autoscraper_schedule_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_job_created', 'autoscraper_scrape_jobs', ['created_at'], unique=False)
    op.create_index('idx_scrape_job_mode', 'autoscraper_scrape_jobs', ['mode'], unique=False)
    op.create_index('idx_scrape_job_priority', 'autoscraper_scrape_jobs', ['priority'], unique=False)
    op.create_index('idx_scrape_job_status', 'autoscraper_scrape_jobs', ['status'], unique=False)
    op.create_table('autoscraper_scrape_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_job_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_created', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('items_skipped', sa.Integer(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['scrape_job_id'], ['autoscraper_scrape_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_run_created', 'autoscraper_scrape_runs', ['created_at'], unique=False)
    op.create_index('idx_scrape_run_type', 'autoscraper_scrape_runs', ['run_type'], unique=False)
    op.create_table('autoscraper_raw_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scrape_run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('posted_date', sa.String(length=255), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['autoscraper_scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_job_checksum', 'autoscraper_raw_jobs', ['checksum'], unique=False)
    op.create_index('idx_raw_job_created', 'autoscraper_raw_jobs', ['created_at'], unique=False)
    op.create_index('idx_raw_job_duplicate', 'autoscraper_raw_jobs', ['is_duplicate'], unique=False)
    op.create_index('idx_raw_job_processed', 'autoscraper_raw_jobs', ['is_processed'], unique=False)
    op.create_table('autoscraper_normalized_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_job_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('remote_allowed', sa.Boolean(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('education_required', sa.String(length=100), nullable=True),
    sa.Column('normalization_confidence', sa.Float(), nullable=True),
    sa.Column('normalization_method', sa.String(length=50), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('job_post_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['raw_job_id'], ['autoscraper_raw_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_normalized_job_created', 'autoscraper_normalized_jobs', ['created_at'], unique=False)
    op.create_index('idx_normalized_job_posted_date', 'autoscraper_normalized_jobs', ['posted_date'], unique=False)
    op.create_index('idx_normalized_job_published', 'autoscraper_normalized_jobs', ['is_published'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_normalized_job_published', table_name='autoscraper_normalized_jobs')
    op.drop_index('idx_normalized_job_posted_date', table_name='autoscraper_normalized_jobs')
    op.drop_index('idx_normalized_job_created', table_name='autoscraper_normalized_jobs')
    op.drop_table('autoscraper_normalized_jobs')
    op.drop_index('idx_raw_job_processed', table_name='autoscraper_raw_jobs')
    op.drop_index('idx_raw_job_duplicate', table_name='autoscraper_raw_jobs')
    op.drop_index('idx_raw_job_created', table_name='autoscraper_raw_jobs')
    op.drop_index('idx_raw_job_checksum', table_name='autoscraper_raw_jobs')
    op.drop_table('autoscraper_raw_jobs')
    op.drop_index('idx_scrape_run_type', table_name='autoscraper_scrape_runs')
    op.drop_index('idx_scrape_run_created', table_name='autoscraper_scrape_runs')
    op.drop_table('autoscraper_scrape_runs')
    op.drop_index('idx_scrape_job_status', table_name='autoscraper_scrape_jobs')
    op.drop_index('idx_scrape_job_priority', table_name='autoscraper_scrape_jobs')
    op.drop_index('idx_scrape_job_mode', table_name='autoscraper_scrape_jobs')
    op.drop_index('idx_scrape_job_created', table_name='autoscraper_scrape_jobs')
    op.drop_table('autoscraper_scrape_jobs')
    op.drop_index('idx_schedule_next_run', table_name='autoscraper_schedule_configs')
    op.drop_index('idx_schedule_enabled', table_name='autoscraper_schedule_configs')
    op.drop_table('autoscraper_schedule_configs')
    op.drop_index('idx_job_board_type', table_name='autoscraper_job_boards')
    op.drop_index('idx_job_board_active', table_name='autoscraper_job_boards')
    op.drop_table('autoscraper_job_boards')
    op.drop_index('idx_engine_status', table_name='autoscraper_engine_state')
    op.drop_index('idx_engine_heartbeat', table_name='autoscraper_engine_state')
    op.drop_table('autoscraper_engine_state')
    # ### end Alembic commands ###