apiVersion: 1

datasources:
  # Prometheus Data Source
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger

  # Jaeger Data Source for Distributed Tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    uid: jaeger
    url: http://jaeger-query:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true

  # Loki Data Source for Log Aggregation
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

  # Elasticsearch Data Source for Advanced Log Analysis
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    url: http://elasticsearch:9200
    database: "remotehive-logs-*"
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "7.10.0"
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level

  # InfluxDB Data Source for Time Series Data
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    database: remotehive
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMode: GET
      keepCookies: []

  # Redis Data Source for Cache Metrics
  - name: Redis
    type: redis-datasource
    access: proxy
    orgId: 1
    url: redis://redis:6379
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0

  # MongoDB Data Source for Database Metrics
  - name: MongoDB
    type: mongodb-datasource
    access: proxy
    orgId: 1
    url: mongodb://mongodb:27017
    database: remotehive
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      authSource: admin
      ssl: false
      sslValidate: true

  # TestData Data Source for Development
  - name: TestData
    type: testdata
    access: proxy
    orgId: 1
    isDefault: false
    version: 1
    editable: true

  # CloudWatch Data Source (if using AWS)
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    orgId: 1
    isDefault: false
    version: 1
    editable: true
    jsonData:
      authType: default
      defaultRegion: us-east-1
      customMetricsNamespaces: 'RemoteHive/Application,RemoteHive/Business'
    secureJsonData:
      accessKey: '${AWS_ACCESS_KEY_ID}'
      secretKey: '${AWS_SECRET_ACCESS_KEY}'

  # Azure Monitor Data Source (if using Azure)
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    orgId: 1
    isDefault: false
    version: 1
    editable: true
    jsonData:
      azureAuthType: msi
      subscriptionId: '${AZURE_SUBSCRIPTION_ID}'
      tenantId: '${AZURE_TENANT_ID}'
      clientId: '${AZURE_CLIENT_ID}'
    secureJsonData:
      clientSecret: '${AZURE_CLIENT_SECRET}'

  # Google Cloud Monitoring Data Source (if using GCP)
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    orgId: 1
    isDefault: false
    version: 1
    editable: true
    jsonData:
      authenticationType: gce
      defaultProject: '${GCP_PROJECT_ID}'
    secureJsonData:
      privateKey: '${GCP_PRIVATE_KEY}'