# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: remotehive-config
  namespace: remotehive
  labels:
    app: remotehive
data:
  # Environment
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  # API Configuration
  CORS_ORIGINS: "https://admin.remotehive.com,https://remotehive.com"
  API_V1_STR: "/api/v1"
  
  # JWT Configuration
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"
  
  # Database Configuration
  MONGODB_DATABASE: "remotehive"
  REDIS_DB: "0"
  
  # Celery Configuration
  CELERY_TASK_SERIALIZER: "json"
  CELERY_RESULT_SERIALIZER: "json"
  CELERY_ACCEPT_CONTENT: "json"
  CELERY_TIMEZONE: "UTC"
  
  # Autoscraper Configuration
  SCRAPER_CONCURRENT_JOBS: "5"
  SCRAPER_DELAY_BETWEEN_REQUESTS: "2"
  SCRAPER_MAX_RETRIES: "3"
  
  # Email Configuration
  SMTP_PORT: "587"
  SMTP_USE_TLS: "true"
  
  # File Upload Configuration
  MAX_FILE_SIZE: "10485760"  # 10MB
  ALLOWED_FILE_TYPES: "pdf,doc,docx,txt"
  
  # Rate Limiting
  RATE_LIMIT_PER_MINUTE: "100"
  
  # Frontend URLs
  ADMIN_URL: "https://admin.remotehive.com"
  PUBLIC_URL: "https://remotehive.com"
---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: remotehive-secrets
  namespace: remotehive
  labels:
    app: remotehive
type: Opaque
data:
  # JWT Secret (base64 encoded)
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  
  # Database credentials (base64 encoded)
  MONGODB_USERNAME: YWRtaW4=  # admin
  MONGODB_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  REDIS_PASSWORD: cmVkaXMxMjM=  # redis123
  
  # NextAuth Secret (base64 encoded)
  NEXTAUTH_SECRET: eW91ci1uZXh0YXV0aC1zZWNyZXQtY2hhbmdlLWluLXByb2R1Y3Rpb24=
  
  # Email credentials (base64 encoded)
  SMTP_USERNAME: eW91ci1lbWFpbEBnbWFpbC5jb20=  # your-email@gmail.com
  SMTP_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==  # your-email-password
  
  # External API keys (base64 encoded)
  CLERK_SECRET_KEY: eW91ci1jbGVyay1zZWNyZXQta2V5
---
# MongoDB ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: remotehive
  labels:
    app: mongodb
data:
  MONGO_INITDB_DATABASE: "remotehive"
  MONGO_INITDB_ROOT_USERNAME: "admin"
---
# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: remotehive
  labels:
    app: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=  # password123
  MONGODB_URL: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvcmVtb3RlaGl2ZT9hdXRoU291cmNlPWFkbWlu
---
# Redis Secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: remotehive
  labels:
    app: redis
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXMxMjM=  # redis123
  REDIS_URL: cmVkaXM6Ly86cmVkaXMxMjNAcmVkaXM6NjM3OS8w  # redis://:redis123@redis:6379/0
---
# TLS Secret for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: remotehive-tls
  namespace: remotehive
  labels:
    app: remotehive
type: kubernetes.io/tls
data:
  # Replace with your actual TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTi...
  tls.key: LS0tLS1CRUdJTi...