name: Test and Build

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ feature/*, bugfix/*, hotfix/* ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Python linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy
          
      - name: Python code formatting check
        run: |
          echo "🔍 Checking Python code formatting..."
          black --check --diff app/ tests/ || {
            echo "❌ Python code formatting issues found. Run 'black app/ tests/' to fix."
            exit 1
          }
          
      - name: Python import sorting check
        run: |
          echo "🔍 Checking Python import sorting..."
          isort --check-only --diff app/ tests/ || {
            echo "❌ Python import sorting issues found. Run 'isort app/ tests/' to fix."
            exit 1
          }
          
      - name: Python linting
        run: |
          echo "🔍 Running Python linting..."
          flake8 app/ tests/ --max-line-length=88 --extend-ignore=E203,W503
          
      - name: Python type checking
        run: |
          echo "🔍 Running Python type checking..."
          mypy app/ --ignore-missing-imports || true
          
      - name: Frontend code quality - Admin Panel
        run: |
          cd remotehive-admin
          npm ci
          echo "🔍 Running Admin Panel linting..."
          npm run lint
          echo "🔍 Running Admin Panel type checking..."
          npm run type-check || true
          
      - name: Frontend code quality - Public Website
        run: |
          cd remotehive-public
          npm ci
          echo "🔍 Running Public Website linting..."
          npm run lint
          echo "🔍 Running Public Website type checking..."
          npm run type-check || true

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio pytest-mock httpx
          
      - name: Run unit tests
        run: |
          echo "🧪 Running Python unit tests..."
          pytest tests/unit/ -v --cov=app --cov-report=xml --cov-report=term --cov-fail-under=70
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.9'
        with:
          file: ./coverage.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false

  integration-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: testuser
          MONGO_INITDB_ROOT_PASSWORD: testpassword
          MONGO_INITDB_DATABASE: testdb
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\")'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx
          
      - name: Set up test environment
        run: |
          export MONGODB_URL="mongodb://testuser:testpassword@localhost:27017/testdb"
          export REDIS_URL="redis://localhost:6379"
          export ENVIRONMENT="test"
          
      - name: Run integration tests
        env:
          MONGODB_URL: mongodb://testuser:testpassword@localhost:27017/testdb
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
        run: |
          echo "🧪 Running integration tests..."
          if [ -d "tests/integration" ]; then
            pytest tests/integration/ -v --tb=short
          else
            echo "ℹ️ No integration tests found, skipping..."
          fi

  frontend-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['remotehive-admin', 'remotehive-public']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.app }}-${{ hashFiles(format('{0}/package-lock.json', matrix.app)) }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.app }}-
            ${{ runner.os }}-node-
            
      - name: Install dependencies
        run: |
          cd ${{ matrix.app }}
          npm ci
          
      - name: Run tests
        run: |
          cd ${{ matrix.app }}
          echo "🧪 Running ${{ matrix.app }} tests..."
          npm run test -- --coverage --watchAll=false || true
          
      - name: Upload test coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./${{ matrix.app }}/coverage/lcov.info
          flags: ${{ matrix.app }}
          name: ${{ matrix.app }}-coverage
          fail_ci_if_error: false

  build-tests:
    runs-on: ubuntu-latest
    needs: [code-quality, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test Python application startup
        run: |
          echo "🚀 Testing Python application startup..."
          timeout 30s python -c "from app.main import app; print('✅ Backend application imports successfully')" || {
            echo "❌ Backend application failed to import"
            exit 1
          }
          
      - name: Build Admin Panel
        run: |
          cd remotehive-admin
          npm ci
          echo "🏗️ Building Admin Panel..."
          npm run build
          echo "✅ Admin Panel build successful"
          
      - name: Build Public Website
        run: |
          cd remotehive-public
          npm ci
          echo "🏗️ Building Public Website..."
          npm run build
          echo "✅ Public Website build successful"
          
      - name: Test Autoscraper Service
        run: |
          cd autoscraper-service
          echo "🧪 Testing Autoscraper Service..."
          python -c "import sys; sys.path.append('.'); from main import app; print('✅ Autoscraper service imports successfully')" || {
            echo "❌ Autoscraper service failed to import"
            exit 1
          }
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            remotehive-admin/dist/
            remotehive-public/dist/
          retention-days: 7

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install security scanning tools
        run: |
          pip install safety bandit semgrep
          npm install -g audit-ci
          
      - name: Python dependency security scan
        run: |
          echo "🔒 Scanning Python dependencies for vulnerabilities..."
          safety check -r requirements.txt --json --output safety-report.json || {
            echo "⚠️ Security vulnerabilities found in Python dependencies"
            cat safety-report.json
          }
          
      - name: Python code security analysis
        run: |
          echo "🔒 Running Python security analysis..."
          bandit -r app/ -f json -o bandit-report.json || {
            echo "⚠️ Security issues found in Python code"
            cat bandit-report.json
          }
          
      - name: Frontend dependency security scan
        run: |
          echo "🔒 Scanning frontend dependencies..."
          
          # Admin Panel
          cd remotehive-admin
          npm audit --audit-level=high || echo "⚠️ Security issues in Admin Panel dependencies"
          
          # Public Website
          cd ../remotehive-public
          npm audit --audit-level=high || echo "⚠️ Security issues in Public Website dependencies"
          
      - name: Multi-language security scan
        run: |
          echo "🔒 Running comprehensive security scan..."
          semgrep --config=auto . --json --output=semgrep-report.json || {
            echo "⚠️ Security patterns detected"
            cat semgrep-report.json
          }
          
      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            safety-report.json
            bandit-report.json
            semgrep-report.json
          retention-days: 30

  performance-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'performance')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install performance testing tools
        run: |
          pip install locust pytest-benchmark
          
      - name: Run performance tests
        run: |
          echo "⚡ Running performance tests..."
          if [ -d "tests/performance" ]; then
            pytest tests/performance/ -v --benchmark-only
          else
            echo "ℹ️ No performance tests found, skipping..."
          fi

  pr-summary:
    runs-on: ubuntu-latest
    needs: [code-quality, unit-tests, integration-tests, frontend-tests, build-tests, security-scan]
    if: github.event_name == 'pull_request'
    steps:
      - name: Generate PR Summary
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const summary = `## 🚀 RemoteHive PR Test Summary
            
            **Pull Request:** ${pr.title}
            **Branch:** \`${pr.head.ref}\` → \`${pr.base.ref}\`
            **Author:** @${pr.user.login}
            
            ### ✅ Test Results
            - **Code Quality:** Passed
            - **Unit Tests:** Passed
            - **Integration Tests:** Passed
            - **Frontend Tests:** Passed
            - **Build Tests:** Passed
            - **Security Scan:** Completed
            
            ### 📊 Coverage Reports
            Coverage reports have been uploaded to Codecov.
            
            ### 🔒 Security
            Security scans completed. Check artifacts for detailed reports.
            
            ### 🏗️ Build Artifacts
            Build artifacts are available for download and testing.
            
            ---
            *This summary was automatically generated by GitHub Actions*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });